apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - name: management-ui
          containerPort: 15672
        - name: amqp
          containerPort: 5672
          
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: ui
    port: 80
    targetPort: management-ui
# This lines works for exporting the rabbitmq connection port
  - name: rabbit
    port: 5672
    targetPort: amqp