apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gabo1208/hello-world-go
          env:
            - name: TARGET
              value: "Go Sample v1"