apiVersion: v1
kind: Namespace
metadata:
  name: rabbitsource
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: cluster
  namespace: rabbitsource
spec:
  replicas: 1
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: rabbitsource
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: cluster
    namespace: rabbitsource
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: subscriber
  namespace: rabbitsource
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  brokers: RABBITMQ_BROKERS
  topic: RABBITMQ_TOPIC
  user:
    secretKeyRef:
      name: RABBITMQ_USER
      key: RABBITMQ_USER
  password:
    secretKeyRef:
      name: RABBITMQ_PASSWORD
      key: RABBITMQ_PASSWORD
  exchange_config:
    name: RABBITMQ_EXCHANGE_CONFIG_NAME
    type: RABBITMQ_EXCHANGE_CONFIG_TYPE
    durable: RABBITMQ_EXCHANGE_CONFIG_DURABLE
    auto_deleted: RABBITMQ_EXCHANGE_CONFIG_AUTO_DELETED
    internal: RABBITMQ_EXCHANGE_CONFIG_INTERNAL
    nowait: RABBITMQ_EXCHANGE_CONFIG_NOWAIT
  queue_config:
    name: RABBITMQ_QUEUE_CONFIG_NAME
    routing_key: RABBITMQ_ROUTING_KEY
    durable: RABBITMQ_QUEUE_CONFIG_DURABLE
    delete_when_unused: RABBITMQ_QUEUE_CONFIG_AUTO_DELETED
    exclusive: RABBITMQ_QUEUE_CONFIG_EXCLUSIVE
    nowait: RABBITMQ_QUEUE_CONFIG_NOWAIT

  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
---
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: heartbeats
  namespace: rabbitsource
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-nightly/knative.dev/eventing/cmd/heartbeats:latest
          name: heartbeats
          args:
            - --period=1
          env:
            - name: POD_NAME
              value: "heartbeats"
            - name: POD_NAMESPACE
              value: "rabbitbroker"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      namespace: rabbitsource