apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chat-svc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: docker.io/gabo1208/chat-service
        ports:
        - name: h2c
          containerPort: 8080
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: R-Type
              value: Probe
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: R-Type
              value: Probe
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: RABBITMQ_URL
            value: "10.96.11.252"
          - name: RABBITMQ_PORT
            value: "5672"