apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-svc-00001
  ports:
  - name: chat
    port: 32080
    targetPort: 8080
  - name: test
    port: 8080
    targetPort: 32080